
version: "3"

services:
  mysqldb:
    container_name: hibadevops
    image: mysql:5.7
    restart: unless-stopped
    environment:
      
      MYSQL_DATABASE: 'achatdb'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  spring_app:
    image: achat
    container_name: achat
    restart: on-failure
    ports:
      - 8082:8082
    depends_on:
      - hibadevops
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://hibaDevops:3306/achatdb?useSSL=false",
           "spring.datasource.username" : "root",
           "spring.datasource.password" : "root",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
    volumes:
      - .m2:/root/.m2
