version: "3.3"

services:
 mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      
    ports:
      - "3306:3306"
    volumes:
      -/home/mysql/data:/var/lib/mysql
    
 spring_app:
    image: hibasbouidevops/achat
    container_name: Projetachat
    restart: on-failure
    ports:
      - "8082:8082"
     depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
          "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

   # volumes:
    #  - .m2:/root/.m2
